# fly.toml app configuration file generated for react-router-prisma-starter on 2023-04-27T11:41:14+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "react-router-prisma-starter"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  cmd = "docker-start.sh"
  entrypoint = "sh"

[deploy]
  strategy = "bluegreen"
  release_command = "pnpm dlx prisma db push --skip-generate"

[env]
  METRICS_PORT = "8081"
  PORT = "8080"
  PRIMARY_REGION = "ams"
  SECURE_AUTH_COOKIE= "true"
  NODE_ENV = "production"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/healthcheck"
    protocol = "http"

[metrics]
  port = 8081
  path = "/metrics"
