name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: remix-prisma-starter-test
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Node CI
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-build-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-node_modules-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Cache playwright deps
        uses: actions/cache@v2
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-build-playwright-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-node_modules-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install playwright deps
        run: |
          npx playwright install-deps
          npx playwright install

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: |
          yarn lint

      - name: E2E
        run: |
          yarn db:migrate
          yarn build
          yarn test:ci
        env:
          SECRET_KEY_BASE: supersecret42069keypleaseitsjokenoangryslavaukraini
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/remix-prisma-starter-test"
