name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      mysql:
        image: mysql:8.0.32
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: remix-prisma-starter-test"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - uses: marocchino/tool-versions-action@v1
        id: versions

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.versions.outputs.nodejs }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Cache playwright deps
        uses: actions/cache@v2
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-build-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-playwright-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          pnpm i
          npx playwright install

      - name: Lint
        run: |
          pnpm prisma generate
          pnpm lint
          pnpm ts-check

      - name: E2E
        run: |
          pnpm prisma db push
          pnpm build
          pnpm test:ci
        env:
          SECRET_KEY_BASE: supersecret42069
          DATABASE_URL: "mysql://root:@localhost:3306/remix-prisma-starter-test"
          SECURE_AUTH_COOKIE: false
          NODE_ENV: production
          PORT: 3001
