name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: remix-prisma-starter-test
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - uses: marocchino/tool-versions-action@v1
        id: versions

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.versions.outputs.nodejs }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Cache playwright deps
        uses: actions/cache@v2
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-build-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-playwright-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          pnpm i
          npx playwright install

      - name: Lint
        run: |
          pnpm run lint

      - name: E2E
        run: |
          pnpm run db:migrate
          pnpm run build
          pnpm run test:ci
        env:
          SECRET_KEY_BASE: supersecret42069keypleaseitsjokenoangryslavaukraini
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/remix-prisma-starter-test"
          PORT: 3001
